# @package _global_

defaults:
  - _self_
  - model: timm.yaml # very important
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - experiment: null

task_name: "robustness"

input_image: "./logbook/resources/imagenet/imagenet_blackswan_100.jpeg"

# 1 - PGD
# 2 - FGSM
# 3 - Pixel Dropout
# 4 - Random Noise
# 5 - Random Brightness

model_robusness: [1,2] #,3,4,5]

target_index: 100